In [1]:
#Gaurav patil A-33
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:
x= np.array([5,15,25,35,45,55]).reshape((-1,1))
y= np.array([5,20,14,32,22,38])
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [5]:
model=LinearRegression().fit(x,y)

r_sq=model.score(x,y)
print("Coefficient of determintation: ", r_sq)

print('Intercept: ',model.intercept_)
print('Slope: ', model.coef_)

Coefficient of determintation:  0.7158756137479542
Intercept:  5.633333333333329
Slope:  [0.54]


In [6]:
y_pred=model.predict(x)
print('Predicted Response: ',y_pred,sep='\n')

Predicted Response: 
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [13]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(20.0,10.0)

#Reading data
data=pd.read_csv('https://raw.githubusercontent.com/Gaurav3435/Dataset/main/headbrain.csv')
print(data.shape)
print(data.head())

#Collecting X and Y
X = data['Head Size(cm^3)'].values
Y = data['Brain Weight(grams)'].values

#Mean X and Y
mean_x=np.mean(X)
mean_y=np.mean(Y)

#Total number of values
n=len(x)


(237, 4)
   Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             3777                 1282
4       1          1             4177                 1590


In [12]:
# Using the formula to calculate m and c
numer = 0
denom = 0
for i in range(n):
  numer += (X[i] - mean_x) * (Y[i] - mean_y)
  denom += (X[i] - mean_x) ** 2
  m = numer / denom
  c = mean_y - (m * mean_x)
  
# Print coefficients
print(m, c)

0.27934490207246887 267.73640093111294
